"""Full functional PRD using the approved Academy document design."""
from pathlib import Path
base = Path(__file__).with_name('build_prd.py').read_text(encoding='utf-8')
exec(base.split('logo=p();')[0])
OUT = ROOT / 'artifacts' / 'Andalusia_Academy_Comprehensive_PRD.docx'
footer.runs[0].text = 'WMS  |  Version 2.0  |  8 September 2026'

# A chapter is a complete functional description, not merely a module name.
chapters = [
('Employee profile and shared navigation', [
('Purpose and access','The employee profile establishes the local workspace identity and active Academy Positions. The application currently stores one local employee profile. Registration is not a password-based login or an organizational identity check.'),
('PF01  Register the workspace','Capture full name, Academy email username, employee ID, department, job title, phone, primary Position, and theme. The email helper forms an andalusia.net address and validates the username. Registration creates the workspace without adding sample tasks or programs. Managers default to Manager Dashboard; other Positions default to My Tasks.'),
('PF02  Maintain the profile','Save changes to personal details, primary Position, and optional additional Positions. Select Manager Dashboard, My Tasks, Plan, Visits, Planner, or Programs as the default view. A non-manager cannot use Manager Dashboard as the default. Show the working week as Sunday to Thursday.'),
('PF03  Profile photograph','Choose an image, preview it, remove it, and save the profile to retain the change. The app rejects files larger than 8 MB and resizes accepted profile images to a maximum dimension of 512 pixels before storing them. This function is separate from the Academy logo.'),
('NV01  Navigate and control appearance','Use the fixed sidebar, collapse it to release workspace width, and restore it with Show Sidebar. Keep the collapse preference on the device. On mobile, expose primary workspaces and a More menu for secondary destinations. Preserve an active-view indication and contextual page title.'),
('NV02  Theme preference','Apply Terracotta, Ocean, Forest, Plum, Midnight, Sandstone, or Rose from the sidebar, top bar, or Profile. Update the appearance immediately and preserve the selected theme in local preferences and the employee profile.'),
('SR01  Global search','After at least two characters, search tasks, programs, assignments, document records, and audit entries. Show up to 30 results with record type and context. Open the relevant task, program, assignment, Documents view, or History view. The current global search does not include networking contacts or visits; use Visits search for those records.'),
('Expected result','Profile changes refresh the visible name, avatar, Position context, and available controls. Closing a dialog or changing a workspace must not silently create a new record. The visible local profile must not be presented as proof of server-enforced user authorization.')]),
('Positions assignments and notifications', [
('GV01  Position model','Use the primary Position together with any additional Positions when checking contribution authority. Academy Manager has full-stage contribution authority and manager completion controls. Registered Positions can view program summaries; editing is organized by the applicable section owner.'),
('GV02  Manager boundaries','Restrict Manager Dashboard, Team Members, Team Member Profile, and Administration through the existing interface guards. Management Summary is available to Academy Manager and Academy Operations Supervisor. Operations navigation is offered to the manager, supervisor, coordinator, and four operational specialist Positions.'),
('GV03  Program creation','The configured creator set contains Academy Manager, Program Operations Executive, MBA/DBA Program Executive, Academy BD & Partnerships Head, and Academy Operations Supervisor. Show New Program only when an active Position belongs to this set.'),
('AS01  Assign and route work','Create workflow work with program, stage, action, owner Position, priority, due date, kind, notes, assigning person, and timestamps. Supported work includes approvals, stage actions, manager tasks, corrective work, reviews, operational follow-ups, incidents, and improvement actions. Avoid another open assignment with the same program, stage, and action.'),
('AS02  Task synchronization','For active-Position assignments without a task mirror, create a workflow task that retains the assignment and program identifiers. The task view also includes assignments that do not yet have mirrors. A single linked assignment must not be shown twice as independent work in the consolidated task list.'),
('AS03  Complete work','Allow the manager or assigned active Position to complete an assignment. Mark its linked task completed at 100 percent. When source references exist, also complete the original operational visit follow-up, resolve the delivery incident, or mark the improvement action Done. Completing work does not independently authorize a lifecycle handoff.'),
('NT01  In-app notifications','Create notifications for assigned work, approval requests, follow-ups, completion, operational review, readiness holds, and program completion. Show unread count and up to 30 recent notifications for active Positions or records without a target Position. Opening one marks it read and opens its assignment or program.'),
('Governance boundary','These are local interface and workflow rules. The baseline does not provide authenticated multi-user sessions or comprehensive server authorization. Position Rule descriptions and module overrides do not establish a production permission boundary. Notifications are in-app records, not email, SMS, or operating-system push alerts.')]),
('Manager Dashboard and crew control', [
('Purpose and access','Give Academy Manager an executive view of the portfolio, workload, readiness, and financial performance. Provide direct paths from an attention item to the record that requires action.'),
('DB01  Executive metrics','Show average program completion, task completion rate, team utilization, current-month sessions, budget utilization, and portfolio margin. Show supporting counts, target comparisons, and compact visual indicators. Program completion is the average of stage progress; task completion uses completed records divided by the task and assignment record count.'),
('DB02  Interpret financial and capacity metrics','Compute inflow as actual revenue plus collected sponsorship, net as inflow less actual cost, and margin as net divided by inflow when inflow is nonzero. Budget utilization compares recorded actual cost with the portfolio budget. Team utilization is a prototype proxy based on open work relative to eight items per Position, capped at 100 percent per member.'),
('DB03  Operational attention','Show active programs, programs at risk, overdue work, blocked work, team members, and open approvals. Present schedule and upcoming delivery, program health, personal work, instructor readiness, finance summaries, and recent recorded activity. Use relevant actions to open Programs, Tasks, Team Members, or the underlying program.'),
('DB04  Launch decisions','Provide a compact launch list with program context, plan-completion checks, expected contribution, manager decision, and reason entry. Start with five rows and allow See All or Show 5. Enable Go only for a complete launch plan. Require a reason for No Go and create corrective work. Do not reopen an already finalized Go from this control.'),
('DB05  Crew assignment','Open Assign Task deliberately rather than showing a permanent long form. Require action title, assigned Position, and due date. Support program and stage context, priority, and notes. Create a Manager Task assignment, notify the Position, and record a program audit event when a program is linked.'),
('DB06  Crew monitoring','Display total, open, overdue, and completed assignments. Sort open work ahead of completed work and by due date. Show the owner, program, stage, due date, priority, and assigning person. Start with five records and expand on demand. Open linked assignments or show general-work details where no linked record exists.'),
('Metric limitation','The built-in executive comparisons use fixed prototype benchmarks, including 80 percent program progress, 90 percent task completion, 80 percent team utilization, an 85 percent budget guardrail, and 20 percent margin. They are interface benchmarks, not approved Academy performance targets or historical trends.')]),
('Tasks and task editing', [
('TK01  Consolidated task view','Show personal tasks and workflow assignments in a table on desktop and readable cards on mobile. Managers can inspect all team Positions; non-managers see records assigned to their active Positions. Display title, project or program, owner, priority, effective status, due date, progress, and Open action.'),
('TK02  Search and filter','Combine text search with project, status, priority, due scope, and manager member selection. Search title, project, category, stage, owner, and notes. Due scopes include all, today, the current week, and overdue. Keep text search visible when secondary mobile filters are collapsed.'),
('TK03  Create and edit','Capture title, project, category, priority, status, deliverable type, progress, start and due dates, estimated and actual hours, recurrence setting, reference URL, and notes. Retain workflow links and Position context while editing an existing record. Require title and dates; block a due date earlier than the start date.'),
('TK04  Classification','Support Not Started, In Progress, Completed, On Hold, and Cancelled; Low, Medium, and High priority; and work categories such as curriculum, content, proposals, materials, recording, assessment, quality review, coordination, delivery, program tracking, client meetings, and administration. Deliverable types classify the expected output rather than generating it.'),
('TK05  Progress controls','Offer a 0 to 100 slider in steps of five and 0, 25, 50, 75, and 100 presets in the editor. A progress value of 100 produces Completed. Lowering a completed record to a nonzero value produces In Progress, or Not Started at zero. Overdue is a display state for open records with a due date before today.'),
('TK06  Complete and delete','Allow the available task completion and inline-progress actions. Eligible ordinary linked assignments can close through those actions; approval, stage-action, and review work keeps its separate workflow controls. Deleting a task requires confirmation and removes that task record. Deleting a mirror does not constitute deletion of its workflow assignment.'),
('TK07  Readability and summaries','Display totals, completed work, overdue and blocked work, due-soon information, status distribution, and attention cards. Bound long lists and provide Show All or Show Less rather than expanding every record by default.'),
('Stored settings and limitations','Recurrence offers None, Daily, Weekly, Monthly, and Quarterly, but the current app stores the setting without a recurring-task generator. Reference links are limited to HTTP or HTTPS. Personal task completion and stage completion remain separate concepts; users must still use the applicable stage controls.')]),
('Team directory and member profiles', [
('Purpose and access','Give Academy Manager a view of workload across Positions and a dedicated profile for each member or Position grouping. The baseline is not a full human-resources system; it combines available directory metadata, the local employee profile, and assigned-work context.'),
('TM01  Directory overview','Display total members, active members with open work, average utilization, overloaded members, underloaded members, and any available on-leave directory status. Provide search and the available department, workload, and status filters.'),
('TM02  Compare workload','Display member name, Position, department, utilization, total tasks, open tasks, overdue tasks, completion, and workload label. Present equivalent member cards on smaller screens. Opening a member selects that Position and shows the dedicated member profile.'),
('TM03  Workload rules','Use High when open work is at least eight items or overdue work is at least three; Medium when open work is at least four; otherwise Low. The utilization proxy is open items divided by eight, capped at 100 percent. Underloaded means fewer than two open items. These are prototype rules, not capacity planning based on working hours.'),
('TM04  Member profile','Show member identity, Position, department, workload, and assigned-work list. Summarize active tasks, completed tasks, on-time indicator, and average task progress. Derive completion percentage from completed divided by total assigned records.'),
('TM05  Profile filters','Combine task text search, project or program, lifecycle stage, effective status, priority, due scope, and record type. Due options include today, this week, overdue, future, or all. Provide Clear filters and list expansion so all matching work is reachable.'),
('TM06  Assign and open work','Use Add Task on a member profile to preselect that member’s Position context. Open tasks in the task editor and unmirrored assignments through their assignment action. Return to Team Members without losing the distinction between directory overview and member work.'),
('Interpretation','The on-time indicator is derived from current total and overdue records, not a historical measure of actual completion timestamps. Member details and leave status are display inputs where available; the app does not provide payroll, leave approvals, personnel onboarding, or a multi-user employee administration workflow.'),
('Example','A Position with nine open items is labelled High even when none is overdue. Selecting that member allows the manager to see the actual assignments behind the indicator and allocate additional work with that Position preselected.')]),
('Weekly monthly and quarterly planning', [
('Purpose','The Planner provides calendar-based views of tasks. It remains a separate destination from the new Plan dashboard, which summarizes operational activities, visits, and follow-ups.'),
('CL01  Weekly planner','Use one Planner navigation entry with Weekly, Monthly, and Quarterly tabs. Navigate between periods and return to the current period using the available controls. The weekly task board follows the Academy Sunday-to-Thursday workweek and supports project, status, and priority filters.'),
('CL02  Weekly day lanes','Display tasks active during each workday with title, project, priority, effective status, progress, and reference link. Open an item to edit it, or use a day’s add action to prefill the date. Keep long day content within the deliberate scroll region.'),
('CL03  Monthly calendar','Display a calendar for the selected month, including seven weekday columns, current-day indication, muted Friday and Saturday cells, and the number of tasks active on each date. A multi-day task can appear on more than one date because membership is based on its active date range.'),
('CL04  Daily task details','Select a calendar date or Today’s Tasks to open that day’s task list. Show task status, project, priority, and effort or progress information. Open records, complete eligible tasks, add a task for that date, and use the available print action.'),
('CL05  Quarterly planner','Display total overlapping tasks, completed tasks, actual hours, and completion rate for the selected quarter. Show its three months with task and completed counts and a compact list of up to seven items per month. Open a visible task for details; use Tasks or Reports for a complete list.'),
('CL06  Period membership','Include records whose start and due date range overlaps the selected period. A task spanning two months contributes to each month it overlaps; month-level counts therefore must not be summed as unique quarterly tasks.'),
('CL07  Printing','Use the browser print flow for daily task output. Let the user choose a printer or Save as PDF where the browser supports it. Printing presents the selected information; it does not schedule reminders or distribute documents.'),
('Boundaries','The weekly calendar and quarterly summaries are based on task dates and current task fields. Recurrence settings do not generate repeated instances. This planner does not synchronize with Outlook, Google Calendar, or employee availability in the local baseline.')]),
('Program portfolio and workspace', [
('PG01  Program portfolio','Show total, active, planned, completed, and on-hold programs and average progress. Provide text search, program-status filter, and current-stage filter. Search program name, type, route, region, and specialty. Use a table on desktop and program cards on mobile.'),
('PG02  Lifecycle intelligence','Present all eight stages with the number of programs currently in each stage and on-track, at-risk, and overdue counts. Explain the selected stage’s purpose and principal actions. Prefer a stage with overdue or at-risk work on first selection; otherwise use a populated stage.'),
('PG03  Program identity','Create a record with name, type, commercial route, specialty, region, start and end dates, expected participants, preliminary budget, objective, and owner context. Initialize all eight stages and the four operational activity records. Program types include Certificate Program, Workshop, Corporate Program, and Webinar; routes are B2C, B2B, and Mixed.'),
('PG04  Workspace overview','Show the selected program’s identifier, name, type, route, region, dates, status, overall progress, current lifecycle stage, key requirements, team context, open work, and recorded activity. Offer detailed stage forms and evidence within expandable areas to keep the initial view readable.'),
('PG05  Stage navigation','Allow inspection of all eight stages while marking the actual current stage independently of the selected stage. Show completed-stage count, stage status, stage progress, and overall progress. Use a horizontal stepper on wider screens and a vertical timeline on phones and portrait tablets.'),
('PG06  Stage control','For each stage, explain owner Positions, prerequisite, completion rule, next handoff, and open assignment count. Show manager requirement checks and enable completion only when the current stage is eligible. Browsing an upcoming stage does not activate it or unlock its inputs.'),
('PG07  Derived program status','Use Completed when both operational and financial closure flags are set; On Hold after readiness No-Go; Delivered after delivery completion; Ready after readiness Go or Conditional Go; otherwise Preparing when overall progress is positive and Planned when it is zero. Overall progress is the mean of the eight stage percentages.'),
('Lifecycle boundary','The eight stages are Request and Greenlight, Curriculum, Instructor Setup, Launch Commercial Operations and Finance, Readiness Delivery and Assessment, Graduate Outcomes, Reporting and Improvement, and Final Closure. Combined stages retain ordered internal sections; they are not independent shortcuts.')]),
('Request greenlight and curriculum', [
('Stage 1 purpose','Capture a justified program request and obtain the manager’s decision before academic production. Program request entry and manager greenlight are separate actions.'),
('RQ01  Draft and submit','Save Draft keeps partial information and does not request approval. Submit for Greenlight checks program name, expected attendees above zero, preliminary budget above zero, objective, and demand evidence. Display missing requirements together and remain editable when validation fails.'),
('RQ02  Approval and return','A valid submission becomes Pending Approval, locks request fields, completes the original submission work, and creates one open manager approval. Approval completes Stage 1 and activates Curriculum. Return makes the request editable again and creates high-priority resubmission work for the program owner Position.'),
('Stage 2 purpose','Prepare an academically complete curriculum pack, perform quality checks, and lock the release for delivery preparation. Curriculum Developer and Curriculum Management contribute; Academy Manager controls the lifecycle handoff.'),
('CU01  Curriculum fields','Record outline, topic, competences, duration, learning outcomes, program structure, assessment blueprint, and draft-pack reference. All eight are required for QA and release. Save partial work as a draft and show progressive completion.'),
('CU02  Academic QA','Require completed greenlight, complete curriculum fields, and all four checks: details, learning outcomes, structure, and assessment. Curriculum Management or Academy Manager can approve QA. Preserve the QA-approved state separately from the locked release.'),
('CU03  Lock and handoff','Lock a valid QA-approved curriculum and record version and release timestamp. Locked fields cannot be freely edited through the draft form. A contributor’s release remains ready for manager stage completion; manager completion closes Curriculum and activates Instructor Setup.'),
('Outputs and assignments','Approval of the request creates curriculum drafting and QA work. Curriculum completion creates instructor shortlisting and selection work, manager fee approval, Legal contract work, and supervisor onboarding work. Each work record retains program, stage, Position, priority, and due date context.'),
('Acceptance example','A request with a zero budget can be kept as a draft but cannot be submitted successfully. A curriculum pack with seven of eight fields cannot pass QA. A locked curriculum does not authorize Instructor Setup until the manager completes the lifecycle handoff.')]),
('Instructor directory profiles and import', [
('IN01  Consolidated instructor network','Combine active instructor master records with program shortlists, evaluations, and selections. Aggregate records by instructor name for a people-first directory and profile. Keep the relationship to each program visible rather than duplicating unrelated instructor identities in the interface.'),
('IN02  Search and filter','Search names, program names, relationship status, internal or external source, level, specialty, region, email, groups, work schedule, and readiness. Filter by a specific program, all programs, or Directory Only for instructors without program assignments.'),
('IN03  Analytics','Show unique instructors, selected or assigned instructors, available capacity, external instructors, ready instructors, and average program load. Present expertise distribution and attention counts for incomplete contracts, incomplete onboarding, and assigned instructors who are not ready.'),
('IN04  Instructor profile','Show available contact details, specialty, region, level, work schedule, availability, notes, and program engagements. For each engagement, expose relationship, rate or fee, assigned groups, source, contract state, onboarding state, and readiness. Provide direct access to the associated program setup.'),
('IN05  Manual entry','Academy Manager can add an instructor with name, email, phone, specialty, level, source, work schedule, availability, region, and notes. Require a name and reject an existing name case-insensitively. Default source to External, schedule to Project Based, and availability to Available.'),
('IN06  Import preview','Accept XLSX or CSV and offer a downloadable instructor template. Use the Instructors sheet when present or the active sheet. Normalize recognized column aliases. Require Name, flag malformed email values, and report duplicates within the file. Preview valid rows, existing matches, and errors before applying the import.'),
('IN07  Commit choices','Merge adds new names and leaves matching existing records unchanged. The replace-matching option updates matching names and adds new names; it does not delete instructors absent from the file. Show added, updated, and skipped counts. Manager test-instructor loading adds sample records for evaluation.'),
('Boundaries','Instructor management is separate from the Visits contact directory. Names are the matching key for instructor aggregation and import, so spelling differences may create distinct identities. The baseline records contracts and onboarding references; it does not issue contracts or deliver an instructor self-service portal.')]),
('Instructor setup and readiness to launch', [
('Stage 3 purpose','Prepare a selected instructor for the program, preserving the separate responsibilities of academic or program operations, Academy Manager, Legal, and the Operations Supervisor.'),
('IS01  Selection','Maintain the program shortlist, record evaluated instructors, and select an instructor. The selected instructor must be included among evaluated instructors before completion. Program Operations and Curriculum Management contribute to selection and engagement details.'),
('IS02  Engagement profile','Capture rate per hour, project-based arrangement, work schedule, level, assigned groups, and instructor source. These six fields must be populated for a complete profile. Keep the agreed fee separate from the descriptive rate field.'),
('IS03  Fee approval','Record a positive agreed fee and manager fee approval. Show approval status with the rest of the instructor readiness checks. Academy Manager can perform this responsibility directly.'),
('IS04  Contract and onboarding','Legal or Academy Manager records signed-contract status and its reference. Operations Supervisor or Academy Manager records onboarding completion and its reference. A checked status without the corresponding reference is incomplete.'),
('IS05  Save and progress','Save each authorized section, retain comments, update the combined setup status, and calculate progress from selection, engagement, fee, contract, and onboarding checks. Close corresponding contribution assignments when their required data is complete.'),
('IS06  Completion gate','Require a nonempty shortlist and evaluation list, a selected evaluated instructor, all engagement fields, a positive approved fee, a signed contract with reference, and completed onboarding with reference. Contributor completion prepares the stage for Academy Manager; manager completion activates the combined launch stage.'),
('Resulting work','Create the next preparation assignments for launch schedule, marketing brief, studio production, financial review, and the manager’s complete launch-plan decision. The instructor directory reflects selected engagements and their readiness state from these program records.'),
('Example','Selecting an instructor and entering a fee is not sufficient. If the contract reference is missing, setup remains incomplete even when Contract Signed is selected. Once every check is met, the manager can close Stage 3 and begin Stage 4.')]),
('Launch planning and manager decisions', [
('Stage 4A purpose','Prepare the full workshop or program launch package before opening commercial execution. The launch plan combines operational, marketing, studio, and financial inputs.'),
('LP01  Program and offer data','Record month, workshop or program name, specialty, level, target audience, duration, teaching method, hands-on format, instructor shooting requirement, supplement change, selling price, launch date, and priority. Capture minimum participants and capacity.'),
('LP02  Supporting evidence','Maintain demand or market research text, reference link, marketing brief, launch comments, schedule confirmation, studio request, and studio readiness. These fields describe the preparation record; the app does not independently perform market research or produce promotional media.'),
('LP03  Financial plan','Record positive launch budget and expected revenue. Display expected contribution as expected revenue minus launch budget. Require positive price, positive minimum participants, positive capacity, and minimum participants no greater than capacity.'),
('LP04  Save and submit','Authorized Operations Supervisor or Program Operations contributors can save and submit the plan. Submission requires all launch checks, including confirmed schedule, studio requested, and studio status Ready. Set Ready for Manager Review and create or retain the manager approval assignment.'),
('LP05  Go decision','Only Academy Manager records Go. A complete launch record is required. Go closes applicable launch and corrective-work assignments, advances the combined stage to its commercial section, and creates applicable B2C and B2B work.'),
('LP06  No Go decision','Require a reason. Record No Go in the launch plan, keep the stage active, and create high-priority corrective work for Program Operations. Retain the decision and reason in recorded history. Launch No Go is distinct from the later readiness No-Go program hold.'),
('LP07  Decision protection','Disable repeated finalization when the launch decision is already Go or the combined stage has completed. The Manager Dashboard and Program Workspace use the same launch readiness and decision logic.'),
('Outputs and boundaries','Successful Go activates commercial work rather than closing all of Stage 4. Commercial completion, four operational activity lanes, supervisor approval, and Finance must still follow. Studio and shooting values are planning controls; no video generation, booking, or external approval service is connected.')]),
('Commercial execution for B2C and B2B', [
('Stage 4B purpose','Track enrollment and payment readiness for consumer programs and opportunity or contract readiness for corporate programs. The route selected on the program determines which commercial sections apply.'),
('CM01  Route applicability','For B2C, require the B2C section; for B2B, require the B2B section; for Mixed, require both. Show nonapplicable routes without treating their missing data as a blocker. Require launch Go before the commercial section is available.'),
('CM02  Consumer enrollment','Capture B2C status, fee, payment method, leads, registered participants, paid participants, and waitlist. Show related completion checks and the current route state. These are aggregate counts, not a complete learner account or payment-processing system.'),
('CM03  Corporate opportunity','Capture B2B account, opportunity stage, proposal reference, contract reference, contract value, and participant count. Program Operations contributes to consumer data; BD and Partnerships contributes to corporate data; the manager retains override authority.'),
('CM04  Validate B2C','Require B2C status Completed for an applicable route. Registered participants must not exceed leads; paid participants must not exceed registered participants; fee and waitlist must be nonnegative. Save operations normalize numeric entry as defined by the form.'),
('CM05  Validate B2B','Require an applicable opportunity to reach Contracted or Won with account, proposal reference, and contract reference present. Contract value and participant count must be nonnegative. A qualified or negotiating opportunity does not satisfy completion.'),
('CM06  Explain blockers','Display route-specific missing conditions, readiness checks, and a completion control. Saving data is separate from Complete Commercial. Do not require a user to guess which of the mixed-route conditions remains outstanding.'),
('CM07  Complete and hand off','When every applicable route passes validation, mark Commercial completed, close its contribution assignments, and activate operational activity work. Stage 4 remains active because operations and Finance still require completion.'),
('Example','In a Mixed program with valid B2C enrollment and a B2B opportunity still at Proposal, Commercial remains incomplete. Moving the corporate opportunity to Contracted with its required references permits completion only if the B2C count rules still hold.'),
('Boundary','References and recorded payment counts are evidence inputs. The app does not collect payments, send proposals, sign contracts, synchronize an external CRM pipeline, or validate that a referenced contract was executed outside the system.')]),
('Operations and operational interaction history', [
('OP01  Operations overview','Select a program and display its four activity lanes, each with owner Position, status, progress, interaction count, and open follow-up count. Show total activities, completed activities, total open follow-ups, and average activity progress. Open a lane in the program workspace.'),
('OP02  Instructors lane','The Instructor Coordination specialist maintains instructor type, agreed operational fee, and final agenda or reference. Completion requires an agenda, at least one recorded interaction, and no open operational follow-ups.'),
('OP03  Logistics and Place lane','The Logistics specialist records venue, budget, and materials. Completion requires venue and materials, at least one interaction, and no open operational follow-ups.'),
('OP04  Attendees lane','The Registration specialist records B2B or B2C attendee type, subtype, fee, payment method, expected count, and attendee-list reference. Completion requires a positive expected count and attendee-list reference, at least one interaction, and no open operational follow-ups.'),
('OP05  Sponsorships lane','The Partnerships Support specialist records sponsor and amount. Completion requires a sponsor and positive amount, at least one interaction, and no open operational follow-ups. Each lane also supports a general activity comment.'),
('OP06  Log Visit or Interaction','From the activity, record target person or organization, date, Physical Location or Online Meeting or Phone Call, objective, outcome, optional evidence reference, and optional follow-up date. Save the interaction into that original activity history and update the activity’s progress and status.'),
('OP07  Assign follow-up','If an operational interaction has a follow-up date, create a Follow-Up assignment for the lane’s owner Position with the source visit identifier. Completing that assignment closes the source follow-up. This automatic workflow link applies to operational interactions, not to new networking visits in Visits.'),
('OP08  Complete and review','Activity owners or the manager complete their lane once its checks pass. Notify the supervisor and close linked activity work. Operations Supervisor or manager reviews all four lanes; return the review if any is incomplete. Approval activates the Finance section and its PMB and Treasury work.'),
('Context and limitation','Operational interactions appear in the Visits database with their original source. They may contain target text without a reusable contact record. New networking contacts and visits do not backfill the operational evidence or complete its follow-ups automatically.')]),
('Readiness checklist and delivery authorization', [
('Stage 5A purpose','Confirm readiness after completion of the combined launch, commercial, operations, and finance stage. The checklist and manager decision protect the handoff into actual delivery.'),
('RD01  Readiness checklist','Maintain agenda, instructor contract, venue, materials, attendee communication, sponsor confirmation, financial clearance, and audiovisual test confirmations. Record preparation comments and the preparing employee.'),
('RD02  Refresh from program evidence','Let Operations Supervisor or Program Coordinator refresh checklist suggestions from existing data. Derive agenda from the instructor activity; contract from signed status plus reference; venue and materials from logistics; attendee communication from positive expected count plus attendee list; and sponsor readiness from completed sponsorship or the B2C route.'),
('RD03  Understand derived checks','The current refresh derives financial-clearance suggestion from positive launch budget and expected revenue, and audiovisual-test suggestion from the existence of a logistics interaction. These are prototype heuristics that need human verification; they are not independent proofs of payment clearance or a successful equipment test.'),
('RD04  Save preparation','Authorized contributors can confirm or change checklist values, enter comments, and save. Update stage progress and close readiness preparation work when all items are checked. Saving the checklist is not the delivery authorization decision.'),
('RD05  Go and Conditional Go','Academy Manager can record Go or Conditional Go only when all readiness checklist items are checked. Preserve the decision, comment, and decision-maker. Conditional Go is a distinct recorded label; it does not bypass incomplete checklist items in the baseline.'),
('RD06  No-Go','Record No-Go when delivery should not proceed. Keep the combined stage active, create corrective readiness work for the Operations Supervisor, notify the supervisor, and derive the program status as On Hold.'),
('RD07  Delivery handoff','A positive readiness decision closes the relevant readiness work and creates delivery execution work for Program Coordinator. The combined stage remains active while sessions, evidence, incidents, and assessment are completed.'),
('Acceptance example','A program with seven confirmed readiness items cannot receive Go or Conditional Go. After the eighth item is confirmed and the manager authorizes delivery, delivery controls become available. A No-Go creates work to resolve the readiness conditions and remains visible as a hold.')]),
('Delivery incidents assessment and certificates', [
('DL01  Delivery record','Program Coordinator or Operations Supervisor maintains delivery status, actual attendance count, instructor arrival, execution-evidence reference, and comments. Update the date, time range, and status of the program’s configured sessions. Session details feed the Schedule workspace.'),
('DL02  Delivery progress and completion','When sessions have begun, change an untouched delivery record to In Progress. Require instructor check-in, execution evidence, every session Completed, and no unresolved incidents before Complete Delivery. Completion opens assessment work within the same combined stage.'),
('DL03  Incident capture','Record incident category, severity, description, owner Position, and due date. Create an Incident assignment with the source incident identifier. High or Critical severity produces high-priority work; other severities produce medium priority. Maintain incident state and creation time.'),
('DL04  Incident resolution','Closing the linked assignment marks the incident Resolved and records its closure time. Unresolved incidents continue to block delivery completion. The incident history remains attached to the program rather than becoming a separate program stage.'),
('AC01  Assessment inputs','Curriculum Management or Program Coordinator records whether assessment is completed, pass count, learner feedback score, certificates issued, results reference, certificate reference, and comments. The manager can contribute through its authority.'),
('AC02  Validation','Pass count must be between zero and actual attendees. Feedback score must be between zero and five. Certificates issued must be between zero and pass count. Require both results and certificate references and a completed assessment flag.'),
('AC03  Complete Stage 5','Valid assessment can complete contributor work and prepare the stage for the manager. Manager lifecycle completion also requires readiness authorization and completed delivery. Close the combined stage only through that controlled sequence.'),
('AC04  Next stage','If graduate outcomes apply, activate Graduate Outcomes and assign Recruitment Head. Otherwise mark Graduate Outcomes N/A and completed, then activate Reporting and Improvement with supervisor work. This keeps all eight stage positions visible even when outcomes are not applicable.'),
('Boundary','The system records attendance and pass counts, assessment evidence, and certificate counts. It does not administer learner examinations, calculate learner-level grades, issue credential documents, or email certificates in the baseline.')]),
('Finance portfolio and stage controls', [
('FN01  Portfolio overview','Show recorded revenue, actual costs, sponsorship collected, net result, margin, and program comparisons. Present revenue mix, profitability, settlement state, and finance closure information. The portfolio table links each row to the program’s Finance section.'),
('FN02  Program records','For each program, show current combined-stage context, finance state, actual revenue, actual cost, sponsorship collected, net result, instructor payment, vendor payment, profit and loss closure, payment evidence, and Open Program.'),
('FN03  Calculations','Use actual revenue plus collected sponsorship as inflow and subtract actual cost for net. Compute margin only with a nonzero inflow denominator. Keep recorded amounts numeric without imposing a hard-coded SAR suffix. The baseline does not implement a multi-currency ledger or conversion.'),
('FN04  PMB contribution','Finance PMB records nonnegative actual revenue and actual cost and confirms final profit and loss closure. Saving can close the corresponding PMB contribution assignment when required values and the closure flag are present.'),
('FN05  Treasury contribution','Finance Treasury records nonnegative sponsorship collected, instructor-paid and vendor-paid flags, and payment-proof reference. Saving can close Treasury work when both settlement flags and evidence are present. The record also supports comments.'),
('FN06  Section gate','Operations must be supervisor-approved before Finance is available within Stage 4. Close Finance only with nonnegative actual revenue and cost, instructor payment confirmed, vendor payment confirmed, payment evidence, and closed profit and loss.'),
('FN07  Manager handoff','A finance contributor can close the section and prepare the combined stage for review, but the Academy Manager completes the lifecycle stage. Manager completion also verifies launch Go, Commercial completion, and Operations approval before activating Readiness.'),
('Outputs','Record Finance Closed, close the PMB and Treasury assignments, and create readiness preparation and manager decision work after the manager handoff. Reflect the same recorded values in the finance portfolio and executive dashboard.'),
('Boundary','Payment flags are recorded confirmations. The app does not execute bank payments, reconcile bank statements, create accounting journal entries, calculate taxes, approve an external invoice, or integrate with a live accounting system.')]),
('Graduate outcomes improvement and final closure', [
('GO01  Graduate outcomes','For applicable programs, Recruitment Head records eligible, consented, job-ready, placement-pool, shortlisted, and placed counts, with evidence and comments. The program’s applicability flag controls this section; Certificate Program is the default applicable type when creating a program.'),
('GO02  Count rules','Require all counts to be nonnegative and no later funnel count to exceed the preceding count: eligible to consented to job-ready to placement pool to shortlisted to placed. Require outcome evidence before completion. Contributor completion waits for manager stage handoff.'),
('GO03  Nonapplicable outcome stage','When outcomes do not apply, retain the stage as N/A and completed rather than removing it from the lifecycle. Continue to Reporting and Improvement. Do not imply that an N/A stage represents completed recruitment placements.'),
('IM01  Course review','Operations Supervisor or Academy Manager records performance-report reference, review-completed confirmation, and comments. The stage is ready only when the report exists, the review is complete, and all improvement actions are Done.'),
('IM02  Improvement actions','Add an action with description, owner Position, and due date. Create an Improvement assignment that retains the source action identifier. Completing that assignment changes the original action to Done and preserves the completion time.'),
('IM03  Review handoff','Contributor completion prepares Reporting and Improvement for the manager. Manager completion closes the stage and creates a Final Closure approval. Open improvement actions remain visible blockers rather than disappearing at report submission.'),
('FC01  Final closure review','Academy Manager checks preceding-stage completion, financial closure, graduate-outcome applicability or completion, completed review, and outstanding prior-stage assignments. The manager control must not treat a completed task mirror as evidence that all prior lifecycle requirements are satisfied.'),
('FC02  Complete the program','Confirm both operational and financial closure and enter lessons learned. Record closing person and timestamp, complete the Final Closure stage at 100 percent, close remaining program assignments through the closure action, write the audit event, and notify the program owner Position.'),
('Example and boundary','A completed performance report with one open improvement action cannot close Stage 7. Final closure records decisions and lessons; it does not archive external files, remove programs from storage, or automatically delete contact history.')]),
('Delivery Schedule workspace', [
('SC01  Session source','Build the schedule from each program’s delivery sessions. Use their stored date, time range, name, and status with program, region, and selected instructor context. Update the source session in Stage 5 to change its schedule information.'),
('SC02  Weekly calendar','Display a seven-day weekly time grid covering the visible 08:00 to 20:00 range. Provide Previous week, Next week, and Today controls. Show program-linked session blocks with time, instructor context, and region. Keep the wide timetable inside its own horizontal scroll area on smaller displays.'),
('SC03  Agenda and filters','Offer calendar and agenda presentation. Support Today and Planned, Today Only, Planned Only, and All Sessions scopes. Planned includes dated sessions from today onward excluding Completed and Cancelled. All Sessions exposes the broader record list.'),
('SC04  Agenda record','Show session date, time, program name and ID, session title, selected instructor, region, status, and Open Program. Sort by date and time. Opening a session navigates to the program’s combined Readiness Delivery and Assessment stage.'),
('SC05  Supporting summaries','Show sessions in the selected week, planned sessions, In Progress sessions, Completed sessions, Cancelled sessions, and instructor coverage. Provide today’s agenda and a compact list of upcoming sessions within seven days.'),
('SC06  Empty states','Explain when there are no sessions for today, the next seven days, or the selected agenda scope. Keep the calendar usable even when no programs exist. A missing time must be represented as not set rather than as a confirmed booking time.'),
('Time interpretation','The grid interprets stored time ranges for visual placement. Unparseable values may use a display fallback. Sessions outside the visible day range need review in the agenda; visual position alone is not a validation of the entered time.'),
('Boundaries','The schedule is a view of configured delivery sessions, not an appointment-booking service. It does not detect instructor or room conflicts, synchronize external calendars, send invitations, support drag-and-drop rescheduling, or provide a standalone session creation workflow.'),
('Acceptance example','After a coordinator changes a configured session’s date, time, or status and saves Delivery, Schedule reflects the same source data. A completed future session remains available in All Sessions but is excluded from the Planned-only scope.')]),
('Plan dashboard and follow-up planning', [
('PL01  Planning scope','Combine operational activities, networking visits, and open visit follow-ups into one dashboard. Provide In progress and Upcoming lanes and summary counts for In progress, Upcoming, Overdue, and Completed. Do not create a second copy of these source records.'),
('PL02  Activity entries','Map activity Not Started to Upcoming and activity In Progress to In progress. Show program, activity, owner Position, and the program start date. Clearly identify that the date is program context, not an independent activity deadline.'),
('PL03  Visit entries','Use each networking visit’s selected status and own date. A visit remains Upcoming until its status is edited, even when overdue. Completed and Cancelled visits do not appear as open visit cards. Operational interaction history contributes completed visit records.'),
('PL04  Follow-up entries','For a visit with a follow-up date and an incomplete follow-up, create a derived planning item unless the visit is Cancelled. Dates up to today appear In progress; later dates appear Upcoming. Completing the follow-up removes this derived open item but preserves the visit history.'),
('PL05  Filter and search','Combine program, activity, and case-insensitive text filters. Search item title, contact or owner detail, activity, and program name. Sort each lane by date, earliest first, with undated records last. Provide Clear filters and an informative no-match state.'),
('PL06  Explain counts','Apply filters before computing summary counts. Overdue means an open item dated before today. A visit and its open follow-up are distinct planning items. Completed counts include finished activities and visits, not unique contacts or unique programs.'),
('PL07  Actions','Open an activity in its original program workspace or a networking visit in its editor. Offer Plan a visit and Visit database shortcuts. Require a saved contact before a new networking visit. Keep long desktop lists scrollable and stack lanes on smaller screens.'),
('Example','An Upcoming visit on 10 October with a follow-up on 12 October yields two planning items. After the visit is marked Completed, only its incomplete follow-up remains open. Closing the follow-up clears that item without deleting the visit record.'),
('Scope boundary','Plan does not currently include all personal tasks, independent plan-item creation, automatic status advancement, or drag-and-drop sequencing. Its date and count rules differ from the calendar-based Planner and must be explained consistently.')]),
('Networking contact directory', [
('NC01  Reusable contacts','Create a stable contact record that can be selected for many visits across programs and activities. Capture contact person, organization, role or job title, email, phone, and relationship notes. Require a nonblank name; organization and communication details are optional.'),
('NC02  Validation','Limit name, organization, and role to 200 characters each; email to 254; phone to 60; and notes to 4000. Apply email-format validation to a nonempty email. Render names and notes as text, including values containing angle brackets or quotation marks.'),
('NC03  Directory view','Show contact name and notes, organization and role, email and phone, total linked visit count, and actions for History, Edit, and Add visit. Keep the contact identifier stable when details are edited.'),
('NC04  Contact history','History changes the view to that contact’s linked visits and displays contact details and relationship notes above the records. Retain a clear way to return to all contacts’ visits. Starting Add visit from a directory row preselects that contact.'),
('NC05  Filters','In the Contact directory, search name, organization, role, email, phone, and notes. Program and activity filters identify contacts through their linked visits. A contact without visits appears when program and activity filters are clear, but does not match a program relationship that has not been recorded.'),
('NC06  Edit propagation','Show revised contact details on all linked networking visits. Store creation timestamp and update timestamp on editing. The current contact record is the source of identity details; no automatic historical snapshot of role or organization is stored at each visit.'),
('NC07  Shared local access','Expose Contacts within Visits for registered local users. The baseline has no networking-specific owner restriction, per-contact sharing control, or complete edit-by-edit audit trail. Production access and data retention are decisions to define separately.'),
('Boundaries','The contact directory is separate from Instructor master data. It does not automatically convert free-text operational interaction targets into contacts. Contact merge, duplicate detection, archive or delete, bulk import, and direct message sending are not implemented.'),
('Acceptance example','Create one contact and link two visits to different programs. Each program filter returns the relevant relationship; History shows the visits for that contact within the current filters. Editing the phone changes the displayed phone without creating another contact.')]),
('Networking visit records and next steps', [
('NVIS01  Visit fields','Choose a saved contact and activity. Select a program or General networking. Require date and nonblank purpose. Support optional time, type, location or meeting reference, outcome, additional notes, follow-up date, next steps, and follow-up-completed flag.'),
('NVIS02  Types and statuses','Support Physical Location, Online Meeting, Phone Call, Event, and Email. Support Upcoming, In Progress, Completed, and Cancelled. These values describe the interaction record; selecting Email does not send a message.'),
('NVIS03  Save validation','Require an existing contact; validate a nonempty program reference against available programs. Require activity, date, and purpose. Require outcome before saving Completed. Reject a follow-up date before the visit date. Limit location to 1000 characters and purpose, outcome, next steps, and notes to 4000 each.'),
('NVIS04  Review records','Show date and time, status, contact and organization, program and activity, purpose, type, location, outcome, notes, follow-up date and state, and Edit visit. Present the newest visit date first. Support both creating and revising a networking visit.'),
('NVIS05  Search and filters','Combine program and activity filters with contact-history scope and text search. Search contact, organization, email, phone, purpose, outcome, location, notes, activity, and program. Clear filters removes search, program and activity restrictions, and the selected contact scope.'),
('NVIS06  Follow-up behavior','Show incomplete follow-up date and next steps in Visits and Plan. Mark the follow-up completed in the visit editor. Cancelled visits remain recorded, but their follow-ups do not count as open planning commitments. No separate workflow assignment is created automatically for a networking follow-up.'),
('NVIS07  Operational source records','Include original operational interactions in the Visits table and label them Operational interaction. Keep their target text, evidence, and original activity context. Use Open activity instead of the networking editor. Operational and networking visits must not be silently merged or duplicated.'),
('NVIS08  Persistence and feedback','Store contact and visit records in the existing application store. Refresh affected views after editing and display saving, saved, or save-failed feedback. Retain networking data across reload and JSON backup export or import.'),
('Acceptance example','A visit may be completed only after an outcome is entered. Its follow-up may remain open until later. Selecting General networking keeps the visit independent of a program while still classifying it by activity.')]),
('Documents reports and recorded history', [
('DC01  Document register','Add a document record after a program exists. Capture name, program, stage, document type, activity context where applicable, reference, and notes. Retain adding person and creation time. Types cover curriculum, QA, evaluations, contracts, onboarding, agenda, marketing, proposals, attendance, results, certificates, payment evidence, reports, recruitment, and other references.'),
('DC02  Find open and remove','Combine search with program, stage, and document-type filters. Search name, type, stage, activity, reference, and program. Open HTTP or HTTPS references externally; display other reference text through the existing reference behavior. Confirm removal of a record and audit it against the program. Removing a reference record does not delete an external file.'),
('RP01  Period task reports','Provide Weekly, Monthly, and Quarterly task reports based on date-range overlap. Show total tasks, completed, In Progress, and actual hours. List task, project, effective status, progress, actual versus estimated hours, and reference link. Report membership follows the stored task collection and is not identical to every manager task-view filter.'),
('RP02  Program report','Select a program and display status, overall progress labelled readiness, open work, and operational follow-up count. List each stage, owner Positions, status, progress, open assignments, and next handoff. This is a program lifecycle summary, not a networking visit report.'),
('RP03  Management Summary','Allow Academy Manager and Operations Supervisor to inspect active programs, programs on hold, open work, and overdue work. Show each program’s current stage, status, progress, open assignment count, and owner. Display a restriction message for other Positions.'),
('RP04  Print and export','Export PDF opens the browser print flow for the report. The existing workbook export produces personal-task sheets and period reports. The baseline does not generate a separate networking workbook or deliver reports automatically by email.'),
('HI01  History modes','Provide completed-task history, Program Audit, and System Audit. Completed-task history lists tasks with Completed status and allows opening their editor; the label does not imply a separate archive store. Program Audit shows program-linked events; System Audit includes other recorded events.'),
('HI02  Audit search','Combine program filtering with search across action, actor, Position, and program identifier. Show action, program or system context, actor, Position, and timestamp. Audit coverage includes explicit workflow and configuration events; do not imply every personal task or networking edit has a full immutable audit record.'),
('Boundary','The document register stores metadata and references, not uploaded binary documents or SharePoint files. Reports describe recorded data and current formulas; they do not replace a learner management, accounting, or regulatory reporting system.')]),
('Administration master data and training', [
('AD01  Position Rules','Academy Manager selects a Position and maintains its description, visible-module list, and core-action descriptions. Save the override, record a system audit event, and refresh navigation context. Reset Override removes that Position’s custom values and returns to the configured rule profile.'),
('AD02  Rule interpretation','Position overrides are recorded configuration, while several actual view and action guards remain defined in application logic. Changing a module label or description alone must not be represented as creating or enforcing a new server permission. Show this production boundary clearly.'),
('AD03  Workflow reference','Display the eight stages, owner Positions, completion requirements, and next handoff as a reference table. This screen explains the implemented lifecycle; it is not a drag-and-drop workflow designer and does not let administrators freely reorder the stages.'),
('AD04  Master data','Select Program Types, Specialties, Regions, Venues, Materials, Sponsors, Instructors, Attendee Subtypes, Payment Methods, or Visit Types. Add a nonblank record and prevent case-insensitive duplicates in that category. Activate or deactivate existing records and retain the audit entry. Remember the selected master category.'),
('AD05  Employee and system views','Show the single local employee’s profile details in Local Employee Registry. Present the local storage architecture and intended integration boundaries in System. These screens do not implement multi-user invitations, organizational identity synchronization, or live Microsoft service connections.'),
('TR01  Guided training','Offer an eight-stage instructional walkthrough containing each stage’s summary, responsible Position, inputs, completion checks, expected system result, and next stage. Show step number and a clickable stage map.'),
('TR02  Training progress','Use Previous, Complete Step, Complete Training, direct stage selection, and Restart. Remember walkthrough progress separately in browser local storage. Completing a training step must not create, advance, approve, or close a live Academy program.'),
('TR03  Distinguish test data','Training is instructional and does not mutate live program records. Profile test-data buttons are different: they add actual sample or test records to the local store. Users should be able to understand which of these two behaviors they are invoking.'),
('Scope','Administrative module descriptions, master-data lists, and training examples describe the current prototype. They do not include a policy engine, tenant administration, security-event console, or general system configuration service.')]),
('Persistence imports backups and test utilities', [
('ST01  Local persistence','Load and save the complete application store through the local server. SQLite is primary storage, store.json is a readable snapshot, and the personal-task workbook is mirrored as Excel. Show Saving, Saved to SQLite, or Save failed. The existing save scheduler batches shortly spaced changes.'),
('ST02  Store contents','Persist employee profile, tasks, programs, assignments, notifications, audit records, documents, master data, settings, and Position Rule overrides. Networking contacts and visits are included within masterData.networking. Default reference data is initialized when required lists are absent or empty.'),
('ST03  Task import','Import XLSX or CSV through Profile. Replace current tasks replaces the task list; Merge combines incoming tasks with current tasks using the existing task-import logic. Preserve other program and configuration sections. A supported imported employee profile may update the local profile. Report errors instead of claiming an unsuccessful import completed.'),
('ST04  Workbook and template','Download the task import template or the current Excel workbook. The workbook includes the overview, profile, personal-task data, and supported weekly, monthly, and quarterly reports. Instructor importing has its own dedicated template and preview workflow.'),
('ST05  JSON backup','Download the complete readable snapshot, including contacts and visits. Import a JSON or text backup to replace the supplied store sections and refresh the interface. This is a restore operation rather than a selective contact merge. Preserve a backup before replacing organizational records.'),
('ST06  Test records','Offer sample tasks, test tasks, sample program, workflow test program, late-stage test program, and Stage 2–8 test program from the collapsed developer-tools area. Instructor test loading is available through instructor management. Test utilities create local records and can affect dashboard counts.'),
('ST07  Clear local data','Require confirmation before clearing profile, tasks, programs, assignments, notifications, documents, audit, master data, and configuration. Clear local training progress and reopen registration. Networking records are removed with master data. Device display preferences may still be held separately in browser storage.'),
('ST08  Service boundary','The local server provides store, export, template, and import endpoints. It is not a synchronization service for concurrent editors. A full-store update can overwrite another editor’s changes, and the baseline does not expose conflict resolution, offline synchronization, or background backup scheduling.'),
('Acceptance example','Export JSON after saving a contact and visit. A restore into a disposable store must retain their identifiers and relationship. Excel task replacement must not be described as an import of program lifecycle or networking records.')]),
('Data relationships states and brand standards', [
('DT01  Core relationships','A program contains eight stages and records for curriculum, instructor setup, launch, commercial work, operations, readiness, delivery, assessment, finance, graduate outcomes, improvement, and closure. Each program has four operational activities; each activity owns its original interactions.'),
('DT02  Cross-record references','An assignment links program, stage, owner Position, and optionally a task mirror and source operational visit, incident, or improvement action. A document links program and stage. A notification can reference an assignment or program. Audit events may be program-specific or system-level.'),
('DT03  Networking relationships','One contact links to many networking visits. Each visit has an optional program reference and an activity classification. Its follow-up is stored on the same visit. Plan reads these sources and computes view entries; it does not duplicate them in a separate plan-item table.'),
('DT04  State vocabularies','Tasks use Not Started, In Progress, Completed, On Hold, and Cancelled, with Overdue derived for open work. Lifecycle stages use Upcoming, Active, Pending Approval, Returned, and Completed. Networking visits use Upcoming, In Progress, Completed, and Cancelled. Keep these vocabularies distinct in labels and filters.'),
('DT05  Dates and counts','Use calendar dates consistently for start, due, visit, and follow-up. Use timestamps for creation and completion metadata. Zero counts and missing data must not be silently presented as verified readiness. Today-based calculations use the browser’s current session date context; refresh is required when a long-running session crosses a date boundary.'),
('BR01  Academy identity','Use the original bilingual Andalusia Academy logo with its proportions preserved. Retain Terracotta as the default theme: primary C17A62, dark 8F4F3B, soft F3E4DF, cream FFF9F6, and ink 55372F. Preserve existing alternate themes rather than introducing isolated colors for new workspaces.'),
('BR02  Usability','Keep explicit labels, visible focus, readable status text, consistent SVG icons, and actionable empty states. Provide Escape dismissal and keyboard focus handling for dialogs. Contain wide tables and calendars within their own scroll regions. Use text as well as color for states.'),
('BR03  Document styling','This PRD retains the same Academy logo and terracotta and cream palette, with readable Word headings, repeated table headers, and page numbers. The branding requirement concerns presentation and does not change workflow validation or authority.'),
('Quality direction','Before broader deployment, test full keyboard flows, screen-reader labels, touch targets, alternate themes, agreed data volumes, and recovery behavior. The local prototype’s existing visual checks do not by themselves certify every accessibility or performance requirement.')]),
('Lifecycle acceptance catalogue', [
('How to use this catalogue','Use these cases for stakeholder UAT and regression testing with an isolated program. Each expected result is an acceptance requirement. Only the focused networking checks listed in the next chapter have current-session execution evidence; the entire lifecycle suite is not claimed to have been rerun for this document.'),
('UAT01  Request','Save an incomplete request as a draft without approval work. Attempt submission with zero expected attendees or missing demand evidence and receive validation. Submit a complete request and get one open manager approval; Return unlocks correction and Approval activates Curriculum.'),
('UAT02  Curriculum','Try QA with a missing draft-pack reference or unchecked QA item and remain blocked. Complete all required content and QA, lock the release, and confirm that contributor completion still requires manager stage handoff.'),
('UAT03  Instructor setup','Attempt completion with a selected but unevaluated instructor, missing fee approval, contract reference, or onboarding reference. Each missing condition blocks readiness. Complete the valid setup and verify the launch preparation work appears after manager completion.'),
('UAT04  Launch','Submit an incomplete launch plan and see its blockers. Record No Go only with a reason and verify corrective work. Record Go with a valid complete plan and verify only applicable commercial routes activate.'),
('UAT05  Commercial and operations','Reject inconsistent B2C counts or incomplete corporate contract references. For Mixed, require both routes. Keep each operational lane incomplete until its required data and interaction exist and its follow-ups are closed. Supervisor review must wait for all four lanes.'),
('UAT06  Finance and readiness','Require both Finance responsibilities and payment evidence before Stage 4 manager completion. Reject Go or Conditional Go when a readiness check is missing. No-Go must create corrective readiness work and show the program On Hold.'),
('UAT07  Delivery and assessment','Block delivery completion for an incomplete session or unresolved incident. Closing the linked incident assignment resolves the incident. Reject pass count above attendance, certificates above passes, feedback outside zero to five, or missing evidence. Complete Stage 5 only through the governed sequence.'),
('UAT08  Outcomes and closure','Reject inconsistent recruitment funnel counts. Preserve N/A outcomes for nonapplicable programs. Block improvement completion for an open action. Require earlier-stage completion, closure controls, and lessons before Final Closure and verify the program-completed notification.')]),
('Workspace acceptance and verification evidence', [
('UAT09  Profile and navigation','Save a profile change and theme preference, reload, and retain them. Restrict manager-only destinations from a non-manager active Position. Expose Plan and Visits through mobile More. Search a program and open the correct record.'),
('UAT10  Tasks and team','Create and edit a task with valid dates; reject due date before start. Confirm status and progress consistency, effective overdue display, Position scoping, and member filters. Verify that eligible assignment completion updates the linked source without independently advancing a lifecycle stage.'),
('UAT11  Planner schedule and reports','Use date overlap consistently across period views. Change a source delivery session and see Schedule update. Keep Completed and Cancelled sessions out of Planned-only. Print the selected report and confirm that its context and rows are correct.'),
('UAT12  Instructors documents and administration','Preview valid instructor import rows and errors before commitment; preserve existing names during merge. Add a document reference and find it with combined filters. Remove only the reference record after confirmation. Add or deactivate master data and record the expected audit event.'),
('UAT13  Contacts and visits','Add and edit a contact, create a linked visit, and inspect contact history. Apply program and activity filters together and search by organization or purpose. Reject Completed without outcome and a follow-up date before the visit. Preserve original operational interaction history.'),
('UAT14  Plan and persistence','Show an open visit and follow-up as separate planning items. Complete the visit while its follow-up remains open, then complete the follow-up and remove its Plan entry. Reload and verify stored contacts and visits. Confirm the JSON backup contains their relationship.'),
('UAT15  Safe utilities','Verify that training steps do not mutate programs, while sample-data utilities do add records. Restore a backup into an isolated environment and confirm all expected sections. Test Clear All Local Data only in a disposable store.'),
('Current verified evidence','The focused networking suite passed syntax, contact creation and editing, visit creation and editing, combined filters, search, validation, legacy-history display, follow-up completion, SQLite reload, JSON export, desktop and mobile overflow checks, mobile navigation, and Escape dismissal. It used a disposable test database rather than changing the original business store.'),
('Remaining checks','The full lifecycle, all user Positions, restore behavior, every theme, complete keyboard accessibility, large data volumes, and simultaneous editing need their own recorded test runs. This expanded PRD is a functional description and UAT baseline, not a declaration that those checks already passed.')]),
('Production boundaries decisions and source baseline', [
('PD01  Identity and permissions','Before shared organizational use, define authenticated users, server-side authorization, networking ownership and visibility, and permissions for export, deletion, and configuration. Keep the local profile and UI Position guards clearly distinguished from these production controls.'),
('PD02  Collaboration and audit','Define concurrent-edit conflict handling, save retries, rollback or recovery, and change history. Networking edits currently retain limited timestamps without complete event history. Personal task and configuration actions also have differing audit coverage; decide the required retention and traceability.'),
('PD03  Networking roadmap','Confirm whether to link legacy operational targets to contacts, merge duplicates, retain contact snapshots at visit time, add contact archive or delete, support bulk contact import, provide networking Excel export, or create assigned tasks from networking follow-ups.'),
('PD04  Planning and reporting roadmap','Confirm whether Plan should include personal tasks and independent activity deadlines, whether recurrence should generate task instances, whether session booking needs conflict detection, and whether dashboard thresholds and workload proxies should be configurable business measures.'),
('PD05  Integrations','Organizational identity, SharePoint document storage, Power Automate approvals, Dataverse or PostgreSQL, external CRM, calendar synchronization, messaging, and accounting integrations are not live services in this local baseline. Their mention in architecture notes is a possible delivery direction, not implemented functionality.'),
('PD06  Operational readiness','Assign business and IT owners for deployment, backups, restore testing, support, retention, expected volumes, and measurable response-time targets. No approved release date, named delivery owner, performance capacity, or business KPI target is assumed by this document.'),
('Source baseline','Prepared from the local README, program-stage flow revision notes, static/index.html, static/networking.js, static/networking.css, server.py, and the networking test files. The original Academy logo is static/logo.png. The functional review covers visible workspaces, forms, event handlers, validation routines, and data persistence as reviewed on 8 September 2026.'),
('Review purpose','Version 2.0 expands the earlier PRD into a description of all major user-facing functionalities and their connected workflow behavior. Reviewers should confirm business terminology, the current scope, the acceptance cases, and the decisions above. The document does not change application behavior or record stakeholder sign-off.')])
]

# Cover contains the business purpose instead of an otherwise empty title page.
logo=p();logo.alignment=WD_ALIGN_PARAGRAPH.CENTER
pic=logo.add_run().add_picture(str(ROOT/'static/logo.png'),width=Inches(1.8))
pic._inline.docPr.set('descr','Original bilingual Andalusia Academy logo')
doc.add_paragraph('Andalusia Academy\nWork Management System',style='Title')
doc.add_paragraph('Comprehensive Product Requirements',style='Subtitle')
p('Version 2.0   |   8 September 2026   |   Draft for stakeholder review',True)
h('Purpose')
p('This document describes the complete set of major user-facing functions in Andalusia Academy’s local Work Management System. It expands the previous PRD beyond a module overview and the Plan and Visits enhancement, so business owners, operators, developers, and testers can understand each function’s inputs, actions, rules, outputs, and limits.')
h('Product scope')
p('The system brings together a controlled eight-stage program lifecycle, position-owned work, manager decisions, instructors, commercial preparation, operations, finance, delivery, outcomes, evidence references, reporting, and local data tools. Plan adds operational planning visibility. Visits adds a reusable networking contact directory and relationship history.')
h('Reading the requirements')
p('Each numbered functional item describes the current baseline or the expected behavior associated with an existing function. Explicit production and roadmap sections identify unimplemented capabilities or decisions. A stored field is not evidence of an external integration: a payment confirmation records a status, a certificate reference records evidence, and an Email visit type records an interaction.')
p('This is a source-grounded functional specification and acceptance baseline. It does not claim full production security, automated business approval, or execution of the entire regression catalogue.',style='Caption')

page(2,'Contents and key terms')
p('Chapters are organized around the user journey, from the employee workspace through program delivery and relationship management to administration and verification.')
for idx,(title,_) in enumerate(chapters):
    par=p(f'{idx+3:02d}  {title}')
    par.paragraph_format.space_after=Pt(3)
    par.paragraph_format.line_spacing=1
    par.runs[0].font.size=Pt(9.3)
par=p(f'{len(chapters)+3:02d}  Position reference and functional coverage')
par.paragraph_format.space_after=Pt(3);par.runs[0].font.size=Pt(9.3)
h('Key terms')
p('Program is the managed Academy offering. Stage is a lifecycle gate. Activity is one of the four operational lanes. Assignment is work owned by a Position and may have a linked task mirror. Plan is the activity and visit dashboard; Planner is the calendar-based task workspace. An operational interaction belongs to a program activity; a networking visit belongs to a reusable contact and optionally a program.')
p('Section numbers also identify the intended page in this edition. Use Word’s Navigation pane to jump between chapter headings.',style='Caption')

for number,(title,sections) in enumerate(chapters,start=3):
    page(number,title)
    for label,text in sections:
        # Purpose and boundary paragraphs give context without turning prose into a table.
        para=doc.add_paragraph()
        para.add_run(label+'  ').bold=True
        para.add_run(text)

# Add a compact appendix matching all Position names used by the implementation.
page(len(chapters)+3,'Position reference and functional coverage')
p('The following Position names are available in the local profile model. Responsibilities describe application contribution areas and do not substitute for the server permissions required in a production deployment.')
table(['Position or group','Functional area'],[
('Academy Manager','Manager Dashboard, crew management, approvals, full-stage contribution, lifecycle completion, instructor management, and Administration.'),
('Academy Operations Supervisor','Program coordination, launch contribution, operational review, onboarding, readiness, delivery support, course review, and management reporting.'),
('Program Operations Executive and MBA/DBA Program Executive','Program creation where configured; program operations contribution according to the relevant section guards.'),
('Academy Curriculum Development Manager and Curriculum Developer','Curriculum preparation and QA responsibilities; Curriculum Management also supports instructor setup and assessment.'),
('Academy BD & Partnerships Head and Business Developer','Corporate and partnership context; BD and Partnerships Head participates in program creation and B2B completion where configured.'),
('Instructor Coordination Logistics Registration and Partnerships Support specialists','Own the four operational lanes and their original interactions and follow-ups.'),
('Program Coordinator','Readiness preparation, delivery sessions, attendance, incidents, and permitted assessment contribution.'),
('Finance PMB and Finance Treasury','Separate financial-result and settlement responsibilities within the Finance section.'),
('Legal Marketing Account Manager and Studio Account Manager','Instructor contracts, launch marketing brief, and studio preparation contributions.'),
('Recruitment Head and Instructor / SME','Graduate outcome responsibility for Recruitment Head; Instructor / SME remains a selectable Position and assignment context.')
],[2.95,3.85],9.2)
h('Coverage statement')
p('This edition covers the visible sidebar destinations, their detail pages, all eight stages and combined-stage subsections, key form actions and validation, import and export tools, stored state, assignment propagation, notifications, and known integration boundaries. Internal formatting helpers and implementation-only rendering functions are not presented as separate business capabilities.')

doc.core_properties.title='Andalusia Academy Comprehensive Product Requirements'
doc.core_properties.subject='All major application functions and acceptance criteria'
doc.core_properties.author='Andalusia Academy'
doc.core_properties.version='2.0'
OUT.parent.mkdir(exist_ok=True)
doc.save(OUT)
print(OUT)
print(f'Planned pages: {len(chapters)+3}')
